version: v1.0
name: Production deployment
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
blocks:
  - name: Deploy
    task:
      jobs:
        - name: Deploy to production
          commands:
            - checkout
            - cache restore
            - bundle install --path .bundle
            - ruby deploy.rb production
      secrets:
        - name: nrvr-demo-deploy-keys
  - name: Sanity check
    task:
      jobs:
        - name: Smoke test
          commands:
            - echo "running smoke tests..."
            - artifact pull workflow build.log
            - 'echo "here''s what we built:"'
            - cat build.log
